### ISSUE TITLE
make ts-textobjs work on function, classes, if, for loops etc.

### ISSUE THREAD

**Issue by JoseConseco** [Jason-M-Chan/ts-textobjects#3]
It would be cool if we could use ts-textobj  not only on parameters but higher level nodes ( conditional staements, functions etc).
Cool plugin btw

**Comment by Jason-M-Chan** [comment]
Check out the [scope textobjects](https://github.com/Jason-M-Chan/ts-textobjects/blob/main/lua/ts-textobjects/actions.lua#L109). They let you target functions/conditionals/etc by using the queries in the nvim-treesitter repository (see [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/lua/locals.scm) for the lua queries, as an example). Personally, I like to use the `goto_outer_scope` ts-textobject action to jump up to the node I want to target, and then use the `a_scope` action to operate on the scope node.

Is there any specific feature you would like to see implemented? If your goal is to target specific node type, then nvim-treesitter/nvim-treesitter-textobjects would be a better option.

**Comment by JoseConseco** [comment]
Ok I can see lua has @scope for :  loops, conditinal statement, functions, classes etc.
Python scope is bit limited (class and functions only). By adding : 
```
[
	(class_definition)
	(function_definition)
	(if_statement)
	(for_statement)
	(while_statement)
] @scope  
```
To python/local.scm I can now target most common language code blocks  (not sure if this is the best way - to override the file in treesitter plugin ..)

I wonder how hard it would be to code the 'inside' version of scope operators  (eg. were we only select inner part of loop, func etc) ?
